### ISSUE TITLE
yarn docker setup fails on MacOS

### ISSUE THREAD

**Issue by ireznik** [graphile/starter#110]
Setup:
- MacOS Catalaina
- yarn v1.21.1
- ZSH & iTerm

Steps to reproduce:
- git clone https://github.com/graphile/starter.git
- yarn docker setup
<img width="1905" alt="yarn docker setup output" src="https://user-images.githubusercontent.com/5952041/74610257-ddfe6a80-50f1-11ea-8143-856095b1cc67.png">

I also tried pruned all containers and images to force rebuild but it did not help.
Found this issue https://github.com/graphile/starter/issues/3 and checked commit history but did not find anything useful in this date range which was very different to the current setup

<img width="1037" alt="generated .env file" src="https://user-images.githubusercontent.com/5952041/74610409-47cb4400-50f3-11ea-8945-5d3052245da3.png">

**Comment by ireznik** [comment]
After help from @benjie the problem was with the progres:11 latest tag of the postgres docker image. 
Setup runs without any issues with version 11.7
11.7: 
https://hub.docker.com/layers/postgres/library/postgres/11.7/images/sha256-aee685b58f28a9523faeaeb0f2324887848f00b3b2e24d13b85726781f31a8bf?context=explore
11:latest: 
https://hub.docker.com/layers/postgres/library/postgres/11/images/sha256-aee685b58f28a9523faeaeb0f2324887848f00b3b2e24d13b85726781f31a8bf?context=explore

**Comment by GerardKetuma** [comment]
Thanks for the update. I was also getting this error on MacOS and this is timely.

**Comment by ireznik** [comment]
> Thanks for the update. I was also getting this error on MacOS and this is timely.

You can build the image with version tag 11.6 - it should run afterwards with 11:latest, but would break again on rebuild

**Comment by benjie** [comment]
Reproduced on Linux :+1: 

Issue is that the `POSTGRES_PASSWORD` envvar is not set. Apparently they've released a breaking change that enforces the requirement for this. I'm going to try and factor it into our setup script.

**Comment by benjie** [comment]
Fixed in https://github.com/graphile/starter/pull/117
