### ISSUE TITLE
Table name users does not conform to schema design in docs

### ISSUE THREAD

**Issue by eleijonmarck** [graphile/starter#115]
The table name in the starter scripts 
https://github.com/graphile/starter/blob/6580e9747b7f829aeb2bbd49c549aef5f0a6a39c/%40app/db/migrations/committed/000001.sql#L120

does not conform to the naming convention started in the schema design guide on postgraphile. 
https://www.graphile.org/postgraphile/postgresql-schema-design/#the-person-table

Expected the tables to be named after the guide like `user` and not `users`.

**Comment by benjie** [comment]
That's by design; Caleb wrote that guide a few years ago and I have the opposite opinion (my opinion is more utalitarian - PostgreSQL uses singular, so if I use plural it's much less likely to clash).

At some point I plan to re-write that guide based around Graphile Starter's schema.
