### ISSUE TITLE
GraphQL Relation discovery in sql not working

### ISSUE THREAD

**Issue by bdombro** [graphile/starter#120]
After uncommenting example commands in current.sql, the following graphql query unexpectedly fails. The reason I expect it to work is in the docs: https://www.graphile.org/postgraphile/relations/

```
query MyQuery {
  posts {
    edges {
      node {
        userByAuthorId {
          email
        }
        body
        headline
      }
    }
  }
}
```

On inspection of `data/schema.graphql`, I notice that authorId is an int, instead of a reference. In other words,
```
type Post {
  authorId: Int
}
```
should probably be
```
type Post {
  author: User!
}
```

Am I missing something? Pardon my ignorance.

Here is my changeset: https://github.com/bdombro/starter/pull/1

**Comment by TimKolberger** [comment]
Postgraphile exposes the relation only if an index for it is found. Postgres does not add an index on foreign key columns automatically - you need to add it yourself.

```sql
create index on app_public.posts (author_id);
```

**Comment by bdombro** [comment]
Thanks so much! I created a pull request to add indexes to this repo: https://github.com/graphile/starter/pull/121

Also contributed to the official docs: https://github.com/graphile/graphile.github.io/pull/205

**Comment by benjie** [comment]
Thanks!
