### ISSUE TITLE
question about db design

### ISSUE THREAD

**Issue by jmarca** [graphile/starter#144]
Hi, I'm not sure where to ask questions, so please redirect me if there is a forum I should use.

I am converting the DB sql to a series of sqitch changes for my uses, and in doing so I noticed that the schema `app_hidden` doesn't seem to be used anywhere.  Is there a purpose for this schema above and beyond `app_private` and `app_public`?  I'm keeping it in for now, but I would rather delete it if the schema serves no purpose.

Also, in the file 000001.sql (committed migrations), there is a minor duplication.  Line 23 (https://github.com/graphile/starter/blob/e90bde90013ac3cc547716fd5ac88833f022fdbe/%40app/db/migrations/committed/000001.sql#L23) says:

```sql
alter default privileges in schema app_hidden grant usage, select on sequences to :DATABASE_VISITOR;
```

but then on line 27 this operation is repeated, but with public and app_public added in as well.

```sql
alter default privileges in schema public, app_public, app_hidden grant usage, select on sequences to :DATABASE_VISITOR;
```

**Comment by charlex** [comment]
@jmarca Questions can be asked in Discord: https://www.graphile.org/postgraphile/community-chat/

I think you can probably remove it, but @benjie might have some reasoning. It just looks like its a placeholder for future purposes to me.

**Comment by benjie** [comment]
Line 23 shouldn't exist, line 27 makes it redundant. It does no harm though.

Feel free to send a PR that removes it:

```
yarn db uncommit
<edit that file>
yarn db commit
git commit -am"Remove redundant SQL statement"
```

**Comment by benjie** [comment]
`app_hidden` is there for future usage, yes. See: https://www.graphile.org/postgraphile/namespaces/#advice

**Comment by jmarca** [comment]
Thanks.  I will direct questions about design decisions to the discord list. 

And I might submit a pull request, but probably not...I don't use yarn, and my dev setup is quite different than "standard".  Plus, as you say, the duplicated statement is redundant and harmless.
