### ISSUE TITLE
missing semicolons

### ISSUE THREAD

**Issue by jmarca** [graphile/starter#149]
(Hopefully *this* one isn't noise!)

Missing semicolons after line 1390 and line 1402.

https://github.com/graphile/starter/blob/1b912b768911e2b0c94eef4eebcdfed6d036f8bd/%40app/db/migrations/committed/000001.sql#L1390

and 

https://github.com/graphile/starter/blob/1b912b768911e2b0c94eef4eebcdfed6d036f8bd/%40app/db/migrations/committed/000001.sql#L1402

**Comment by jmarca** [comment]
never mind.  It was noise.

**Comment by benjie** [comment]
Probably should have semicolons there 🤷‍♂️
