### ISSUE TITLE
Question about altering app_public.confirm_account_deletion for organization_memberships

### ISSUE THREAD

**Issue by jmarca** [graphile/starter#152]
I'm sure there was discussion about this when it was developed, and I apologize if I'm dragging up an issue that was settled already.  Also sorry for the long issue text.  I'm genuinely not sure how to deal with this and not sure how to express my issue clearly.

But... I don't like the fact that inserting organizations into the database ends up needing to alter the app_public.confirm_account_deletion function.

Why?  I like small projects with clear dependencies, and so I have split the db into pieces, and up to this point is neatly fits into a bunch of little projects (schemas, roles, utility function, etc) and then big project for user_system and a medium project for organizations.

Everything works, and conceptually I can install my user_system, and it will pull in what it needs, or instead I can start by installing organizations, and it will pull in user_system and its dependencies, etc.  Everything works except for this part:

https://github.com/graphile/starter/blob/1b912b768911e2b0c94eef4eebcdfed6d036f8bd/%40app/db/migrations/committed/000001.sql#L1457

Changing the `confirm_account_deletion` function doesn't fit anywhere.  

If I put the change inside of my user_system repo, then that implies that user_system must know about the organizations stuff.  That is clearly wrong.

But if I put the `create or replace function` update inside of the organizations stuff, then that implies that there can be no other db addition that can do the same thing (prevent deletion of users if they are needed for some reason).  

The problem became apparent because I'm using sqitch, and sqitch likes to have "revert" functions.  If I revert the modification from inside organizations project, then it must revert to the previous state.   That's where I noticed the problem.  What is the "previous state"?  

Suppose there is another db addition/feature, call it B, that *also* wants to prevent deletion of a user for some reason.  Following the approach of organizations, that would mean another call to `CREATE OR REPLACE FUNCTION...`, but how to write that update?  It should not be the case that B must consider all other possible db additions, just as organizations doesn't care about any other db additions.  Yes I can hand-roll each solution, but I'd like a starter system to be able to mix and match elements without much effort.

What I really want is some way to prevent deletion that is more of a plugin, or otherwise doesn't directly touch the "confirm_account_deletion" function.  

My first thought was to use row-level security policies. I tried and failed to do something like:

```sql
CREATE POLICY cannot_delete_organization_owner
ON app_public.users
AS RESTRICTIVE
FOR DELETE
TO PUBLIC
USING ( id not in (select distinct om.user_id from app_public.organization_memberships om
          where is_owner is true )
);
```

It seems to me that *should* work, but it *doesn't*.  As the superuser role, I can delete users who are owners of organizations, and so it won't work to stop the function from doing that either.  But maybe I'm doing something wrong as I don't really know what I'm doing with policies...they are a new feature for me.

Another approach might be to define the organization-users join table using table inheritance, and then use `on delete restrict` for the owner version of the table.

Or maybe a convention that new db features need to implement a function called `[feature]_confirm_account_deletion(user_id uuid) returns bool` that votes yes or no whether the given  user can be deleted?  Then modify the original confirm_account_deletion to search the catalog for all such functions and call all of them until it hits a false.

Or maybe a table that includes blocking tables and conditions that can be called by the confirm delete function to see what conditions should be checked?

I don't know.  But I do know that my current solution (tagging user_system and implementing the change there) is brittle and will eventually break.

**Comment by benjie** [comment]
ON DELETE clauses on foreign keys are really just triggers. You want a selective on delete, so you could accomplish this with adding a trigger to the table that raises an exception when appropriate.

**Comment by jmarca** [comment]
Excellent!  Thanks.
