### ISSUE TITLE
Nuxt Starter link not working

### ISSUE THREAD

**Issue by santicros** [graphile/starter#158]
Hey! I really like the postgraphile project. I'm using Nuxt.js and saw that there was a Starter made with it, but the link is not working.
Would really like to check that out! Thanks!!

**Comment by benjie** [comment]
Paging @JoeSchr Does the link need updating? Is it this now?

https://github.com/JoeSchr/graphile-starter

**Comment by JoeSchr** [comment]
Yeah, that's it. Sadly it has been a bit abandoned under RL pressure the last couple of weeks, but I hope to get to update it soon.

At least it should put you in the right direction @santicros and if you get to fix some stuff or drive it forward I would be happy to receive PRs! Good Luck!
