### ISSUE TITLE
Password strength indicator required

### ISSUE THREAD

**Issue by benjie** [graphile/starter#16]

**Comment by MobliMic** [comment]
I have started doing some work on this issue. Is this the sort of thing you are looking for?

![image](https://user-images.githubusercontent.com/4713282/71271091-0ca6d180-234b-11ea-91d2-5e315fd237dd.png)

**Comment by benjie** [comment]
Nice; yeah this is the kind of thing I had in mind! Could you also rename "password" to "passphrase" while you're at it? I should try and ban the word `password` from my vocabulary.

**Comment by MobliMic** [comment]
Opened PR #91

**Comment by benjie** [comment]
Implemented in #91
