### ISSUE TITLE
Don't compile ROOT_URL/etc into Next bundle (use window variable)

### ISSUE THREAD

**Issue by benjie** [graphile/starter#162]
Otherwise we can't easily promote staging to production (requires rebuild)

**Comment by aortbals** [comment]
Hey @benjie - I've made this change locally to a project and also modified the production Dockerfile to support building a single image for multiple environments and multiple entry points (server, worker). This means you can build and store one image that can be promoted and also used for either the server or worker. Would you be interested in a PR?

**Comment by benjie** [comment]
Yes please :raised_hands:

**Comment by benjie** [comment]
Hey @aortbals have you had a change to look at this yet?

**Comment by aortbals** [comment]
I'll get a PR up this week, thanks for the reminder!

**Comment by benjie** [comment]
Awesome :+1:

**Comment by DylanVann** [comment]
I thought I could work on this after refactoring environment variables (https://github.com/graphile/starter/pull/234), but it seems like it's already done in `@app/client/src/next.config.js`.

**Comment by benjie** [comment]
Ah yes, I did this, thanks 👍
