### ISSUE TITLE
Can't replace autogenerated passwords with arbitrary custom passwords in setup.js

### ISSUE THREAD

**Issue by jmarca** [graphile/starter#164]
Trying to hunt down a bug in my sqitch-based setup, I discovered that using database passwords with spaces in them will break how ROLEs are created in setup.js.

This line and others:

https://github.com/graphile/starter/blob/0af7c5ce1655c8d1071cc813fd20edfb33040aa4/scripts/setup.js#L310

In my script I have a little function like this:

```sql
CREATE FUNCTION pg_temp.foo(_role text, _pass text)
  RETURNS void AS
$func$
BEGIN
    perform true from pg_roles where rolname = _role;
    if not found then
        EXECUTE 'CREATE ROLE ' ||
          quote_ident(_role) ||
        ' WITH LOGIN PASSWORD ' ||
        quote_literal(_pass) ||
        ' NOINHERIT';

    end if;
END
$func$  LANGUAGE plpgsql;

SELECT pg_temp.foo(:'DATABASE_AUTHENTICATOR', :'DATABASE_AUTHENTICATOR_PASSWORD');
```

It is not something that can be directly copied into setup.js, and it is a bit of a hack (I'm sure someone with better psql-fu can improve it), but it definitely allows me to uses spaces in passwords.

**Comment by jmarca** [comment]
Okay that sounds fair.  

Ran across this because I'm trying to reproduce what is in .env *without* running yarn setup. Because I'm using sqitch, not graphile/migrate, yarn setup will fail when it gets to the part about clobbering the db.

So in my .env file, I have my usernames and passwords used for my sqitch deployment, which is how I discovered this.

(My hobby is doing things "A Different Way"™ and finding out that things break).

I guess the larger issue is that setup both configures the environment file .env *and* clobbers & (re)creates the database.

**Comment by benjie** [comment]
What do you propose?

**Comment by jmarca** [comment]
I think the least disruptive way would be to split the command in package.json.

Something like:

```json
  "scripts": {
    "setup": "yarn && yarn setup:env && yarn setup:db",
    "setup:env": "node ./scripts/setup.js --env",
    "setup:db": "node ./scripts/setup.js --db",
   ...
  }
```

Maybe better to split setup.js into two scripts, in order to properly message the user at the end of the script.  Or use command line flags like I penciled in above.  I'm hacking up a branch right now with this idea.

Then, if I want to slot in my db-setup routine, I'd run `yarn setup:env`, then run run my sqitch stuff to setup the DB (sourcing the .env file to get consistent variables), then launch the server with `yarn start`. (Although sqitch does not use .env file, but rather a sqitch.conf file, so I'll probably wrap it with a short yarn script to translate).

**Comment by jmarca** [comment]
Okay my suggested change is in pull request #165.  Mostly to flesh out the idea.  Please suggest changes, or reject.

Seems to work on my end.

**Comment by benjie** [comment]
Closing in favour of #165
