### ISSUE TITLE
Create organization main menu option problem

### ISSUE THREAD

**Issue by it-all** [graphile/starter#175]
I'm not sure exactly how I got to this state, but I have created an organization, which I can edit at https://graphile-starter.herokuapp.com/o/it-all.com/settings/

However, from the main menu, I have a "Create organization" option which sends me https://graphile-starter.herokuapp.com/create-organization. This gives me an error when I enter my current organization (already taken or the like).

I think this is a bug, but not positive. Possibly the Create organization menu option should be replaced with Edit organization.

**Comment by benjie** [comment]
You may have more than one organization, like on GitHub. This is not a bug.

**Comment by it-all** [comment]
Thanks.
