### ISSUE TITLE
Envvar validation

### ISSUE THREAD

**Issue by justinr1234** [graphile/starter#186]
Would something like this work? https://github.com/af/envalid

**Comment by benjie** [comment]
You could use that if you wish, yes. I don't want it in the starter though :+1:

**Comment by justinr1234** [comment]
@benjie What solution would you recommend? I’d be willing to code it, but want an approved solution before I move forward. I read somewhere in your docs or code that you’d be looking for a contributor to validate prosper env vars. Any guidance is appreciated! Thanks!

**Comment by benjie** [comment]
Did I? I don't remember that... Probably just needs a few `if (!process.env.REQUIRED_SOMETHING_OR_OTHER) { throw new Error("SENSIBLE ERROR") }` - I don't want to add another library for this.

**Comment by justinr1234** [comment]
@benjie got it! Makes sense. It was in the README, under `Building the production docker image`:

> Currently if you miss required envvars weird things will happen; we don't currently have environment validation (PRs welcome!).

**Comment by benjie** [comment]
Ah, that's specifically relating to the docker environmental variables. Not sure how to do that :)
