### ISSUE TITLE
Adding a new TypeScript file to @app/worker doesn't trigger the watcher to build TSC

### ISSUE THREAD

**Issue by lundcm** [graphile/starter#193]
Typically the watcher will trigger a TypeScript build when a file changes:

```
(TSC) 
(TSC) 9:55:39 AM - File change detected. Starting incremental compilation...
(TSC)
```

When you add a new file in the `worker/src/tasks` (maybe others, but I'm mainly using watcher at the moment), the watcher doesn't pick anything up until you restart `yarn start`. I tried with both valid TS and invalid TS where I was expecting to see some errors. After restarting it attempts to build the new files and shows you the errors before exiting completely. So if you're adding a new file that has errors you have to keep restarting `yarn start` until you get a valid build before watch works like you'd expect.

**Comment by benjie** [comment]
Awesomely, upgrading TypeScript seems to have finally fixed this bug!
