### ISSUE TITLE
Why is avoidOptionals.field true?

### ISSUE THREAD

**Issue by heri16** [graphile/starter#207]
https://github.com/graphile/starter/blob/26d0d18ff83a3ba73e5139638d8d45ecfd5f030e/%40app/graphql/codegen.yml#L4-L6

Why is avoidOptionals.field true?

**Comment by benjie** [comment]
It improves type accuracy. The fields aren’t truly optional; they are guaranteed by the GraphQL spec to be returned, whether null or otherwise.
