### ISSUE TITLE
Nuxt starter does not `yarn run start`

### ISSUE THREAD

**Issue by MichaelJCole** [graphile/starter#213]
### Summary

The starter kit at https://github.com/JoeSchr/graphile-starter does not start.

### Steps to reproduce

I setup the official starter, and then tried to start the nuxt version:

```
git clone git@github.com:JoeSchr/graphile-starter.git graphile-nuxt
cd graphile-nuxt
yarn
yarn run setup
```
`yarn run setup` failed with this output:

```
[1/4] Resolving packages...
success Already up-to-date.
? What would you like to call your database? graphile_nuxt
? What's the hostname of your database server (include :port if it's not the default :5432)? localhost
? Please enter a superuser connection string to the database server (so we can drop/create the 'graphile_nuxt' and 'graphile_nuxt_shadow' databases) - IMPORTANT: it must not be a connection 
to the 'graphile_nuxt' database itself, instead try 'template1'. postgres://postgres:changepassword@localhost:5432/demo

 FATAL  ⨯ Unable to compile TypeScript:                                                                                                                                             19:50:01  
nuxt.config.ts:2:42 - error TS2307: Cannot find module '@app/config/dist/index'.

2 import { projectName, companyName } from "@app/config/dist/index"; //! imported here because it otherwise complains about not finding it and also overwrits gql query results
                                           ~~~~~~~~~~~~~~~~~~~~~~~~


  nuxt.config.ts:2:42 - error TS2307: Cannot find module '@app/config/dist/index'.

  2 import { projectName, companyName } from "@app/config/dist/index"; //! imported here because it otherwise complains about not finding it and also overwrits gql query results
                                             ~~~~~~~~~~~~~~~~~~~~~~~~

  at createTSError (/home/michael/myproject/graphile-nuxt/node_modules/ts-node/src/index.ts:293:12)
  at reportTSError (/home/michael/myproject/graphile-nuxt/node_modules/ts-node/src/index.ts:297:19)
  at getOutput (/home/michael/myproject/graphile-nuxt/node_modules/ts-node/src/index.ts:399:34)
  at Object.compile (/home/michael/myproject/graphile-nuxt/node_modules/ts-node/src/index.ts:457:32)
  at Object.m._compile (/home/michael/myproject/graphile-nuxt/node_modules/ts-node/src/index.ts:536:43)
  at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
  at Object.require.extensions.<computed> [as .ts] (/home/michael/myproject/graphile-nuxt/node_modules/ts-node/src/index.ts:539:12)
  at /home/michael/myproject/graphile-nuxt/node_modules/esm/esm.js:1:231006
  at /home/michael/myproject/graphile-nuxt/node_modules/esm/esm.js:1:231041
  at /home/michael/myproject/graphile-nuxt/node_modules/esm/esm.js:1:231254


   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                                                         │
   │   ✖ Nuxt Fatal Error                                                                                                                                    │
   │                                                                                                                                                         │
   │   TSError: ⨯ Unable to compile TypeScript:                                                                                                              │
   │   nuxt.config.ts:2:42 - error TS2307: Cannot find module '@app/config/dist/index'.                                                                      │
   │                                                                                                                                                         │
   │   2 import { projectName, companyName } from "@app/config/dist/index"; //! imported here because it otherwise complains about not finding it and also   │
   │   overwrits gql query results                                                                                                                           │
   │   ~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                              │
   │                                                                                                                                                         │
   │                                                                                                                                                         │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Error: Process exited with status '1' (running 'yarn server build')
    at spawnSync (/home/michael/myproject/graphile-nuxt/scripts/setup.js:45:13)
    at main (/home/michael/myproject/graphile-nuxt/scripts/setup.js:342:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected results

I thought it would setup like the other starter

### Actual results

Looks like it had a compile error

### Additional context

Here is my setup:  https://docs.google.com/document/d/1DyXpd3vbS0l9V4Iud5INnLNPl6bUB_CG7oPn4R1M_D4/edit?usp=sharing

### Possible Solution

I'm wondering if PostGraphile could integrated into another Vue starter kit that is more maintained.  My goal is to use [Quasar as the front-end](https://quasar.dev/) possibly using this [Apollo client](https://github.com/quasarframework/app-extension-apollo)

**Comment by benjie** [comment]
Hi @MichaelJCole; best to file this issue against JoeSchr/graphile-starter directly (or create your own starter fork designed in the way you'd like) - you can also reach JoeSchr on Discord I think. The current state of Graphile Starter is pretty much as far into this space as I want to dabble right now otherwise I'll be spreading myself too thin, I don't have time to explicitly demonstrate PostGraphile with all the various frontend frameworks. PostGraphile's job is really on the backend and you should be able to use whatever frontend you wish with it (since it's just GraphQL at the end of the day). I built this React frontend because I needed it for my own projects, and shared it because I love OSS :)

**Comment by MichaelJCole** [comment]
@benjie Yes, I totally get how these starter projects are too much to maintain.  **I think you should deprecate of both of them.**

The react starter project obscured PostGraphile.  I spent more time thinking about Next (e.g. CSRF token by SSR) than PostGraphile while evaluating it.  Essentially, I was asking you about Next on the discord yesterday :-)

It might be better to remove the link to the Vue one - it communicates incomplete work.  I remember a comment from Joe he didn't have time to maintain it.

I think these two starter repos were more "in the way" than helpful.

I'd love a very simple TodoMVC-like example FE, so I can focus on PostGraphile.  It should have auth - because PostGraphile's auth system in sql is so unique.

I also evaluated Hasura, which lacks integrated auth.  They delegate auth to "Hasura Backend Plus", Auth0 or KeyCloak - but HBP is incomplete and KeyCloak is an enterprise monster.  PostGraphile's integrated auth is a big benefit over Hasura.

I'm passing on Apollo because I want something for a small team and more open source than how they handled Meteor.

Anyways Benjie, that's my experience so far.  Thanks for reading!

**Comment by xvaara** [comment]
I did a test with nuxt: https://gist.github.com/xvaara/d344c90fdb914e3c3ad8024560db7f79

But I don't have the time at the moment to make that in to complete fork. I don't use nuxt my self, and I'm basically waiting for vue3 version of libraries to mature.

But after there is official docs/support for vue3 SSR, I was thinking of doing a starter for vue3 + [villus](https://github.com/logaretm/villus).

I spent some time to get to know starter, and I have to say Benjie did a better job teaching me how to do graphql in starter than any other documentation I have read. Next isn't that bad. Just remove it from ssr middleware... that's it. Fix CSRF... just enable it in a cookie or something. I did a /token that generates/returns a token.

**Comment by benjie** [comment]
> I think you should deprecate of both of them.

They're not my projects, they're not under my control (or responsibility). I could remove the links but :shrug: I don't see value in that. Maybe put a bigger disclaimer in front of it ;)

> The react starter project obscured PostGraphile. I spent more time thinking about Next (e.g. CSRF token by SSR) than PostGraphile while evaluating it. Essentially, I was asking you about Next on the discord yesterday :-)

Yeah, we need to communicate better that this is a SaaS starter for people already familiar with all the technologies in it, not a "Here's how you get started with PostGraphile" repo, because it 100% is not that! The aim is for people already well established in these technologies, here's a thing you can use to get a SaaS started with everything you want (end-to-end tests, linting, CI, deployment, migrations, type safetly, security, user management, etc etc etc) so you don't have to spend the first 3 weeks scraping all this tooling up together yourself.

> I'd love a very simple TodoMVC-like example FE, so I can focus on PostGraphile. It should have auth - because PostGraphile's auth system in sql is so unique.

I definitely need to build more simple example projects with less tooling to help people get started. At the moment this is mostly served by the following:

- https://www.graphile.org/postgraphile/postgresql-schema-design/
- https://github.com/graphile/postgraphile/tree/v4/examples/forum
- https://github.com/graphile/examples
- And arguably https://github.com/graphile/demo

> Benjie did a better job teaching me how to do graphql in starter than any other documentation I have read

Thanks! I refer to the starter _heavily_ when people ask me "how do I do tests?" "how do I do codegen?" "how do roles work?" etc etc. It's a great demonstration of a lot of techniques, for example how to use fragments with your React components. It has been absolutely invaluable for me.

**Comment by benjie** [comment]
I've attempted to communicate some of the outcome of this discussion in this commit:

https://github.com/graphile/starter/commit/558605988e25201b4842561fe6ebcdab000945e3
