### ISSUE TITLE
Accessing multiple databases through postgraphile

### ISSUE THREAD

**Issue by KrishnaPG** [graphile/starter#225]
### Summary

This starter template has created `users` in an app specific database during the setup, which is great. This `users` and related tables are used for auth etc., which is fine. However, I have another database (with its own set of tables) that I would like to additionally get access to through the postgraphile.

Wondering if that is possible, and if so how to go about it?

### Additional context

Would like to keep the users database separate and also need to have access to additional databases exposed through postgraphile. Would like to know what is the best way to achieve that, using this template? Is it possible?

**Comment by benjie** [comment]
PostGraphile is designed for a single database; using two databases causes messy and expensive joining of data, multiple SQL queries, higher latency and is just plain undesirable. If you must do that there are solutions out there like GraphQL Mesh, schema stitching, etc; but they are well beyond the scope of this repo. Good luck 👍
