### ISSUE TITLE
Strange behaviour when pressing Sign in several times

### ISSUE THREAD

**Issue by cryptedx** [graphile/starter#231]
### Summary

When I click `Sign in ` multiple times it adds 'login%3Fnext%3D%252F' to the url.

1. click: ![image](https://user-images.githubusercontent.com/20707078/104127678-cd875c00-5363-11eb-95fd-6b0c0ca7f749.png)

2. click: ![image](https://user-images.githubusercontent.com/20707078/104127688-df68ff00-5363-11eb-8e01-b3776f019e65.png)

3. click: ![image](https://user-images.githubusercontent.com/20707078/104127699-f0b20b80-5363-11eb-9c55-e5192e5d7663.png)

4. click: ![image](https://user-images.githubusercontent.com/20707078/104127719-09babc80-5364-11eb-8453-e0e62ba0c078.png)

![Jan-10-2021 16-54-14](https://user-images.githubusercontent.com/20707078/104127832-a5e4c380-5364-11eb-8e31-57eca97b5f62.gif)

### Steps to reproduce

Just click multiple times on `Sign in`

It should just refresh the page?!

### Additional context

Ubuntu 20.04.1 LTS
node v14.15.1
psql (PostgreSQL) 12.5
yarn 1.22.5
starter: I am using the lastest master branch

**Comment by benjie** [comment]
Ooo good catch. The sign in link at the top right shouldn't be present on that page!
