### ISSUE TITLE
Heroku Demo App Reset Password flow is broken

### ISSUE THREAD

**Issue by vinzenzweber** [graphile/starter#252]
### Summary

Heroku Demo App throws an error when trying to set a new password via link from email
`GraphQL error: function app_private.reset_password(unknown, unknown, unknown) does not exist`

### Steps to reproduce

1. Create account with email/password 
https://graphile-starter.herokuapp.com/register
2. Logout
3. Enter email in forgot password form 
https://graphile-starter.herokuapp.com/forgot
4. Receive email and click on **Change Passphrase** link 
https://graphile-starter.herokuapp.com/reset?user_id=xyz&token=xyz
5. Enter a new passphrase and click **Reset passphrase**

### Expected results

Set a new passphrase and receive a success message.

### Actual results

Request fails with error `GraphQL error: function app_private.reset_password(unknown, unknown, unknown) does not exist`

**Comment by benjie** [comment]
Unexpected. I wonder if the UUID  became corrupt and couldn't be casted. Thanks for the report I'll look into it when I get a chance :+1:

**Comment by benjie** [comment]
Turns out this was a deployment automation issue (I messed up the Heroku config). Fixed :+1:
