### ISSUE TITLE
Filter error in testing query

### ISSUE THREAD

**Issue by libinvarkey** [graphile/starter#265]
When using filter in error got error
[GraphQLError: Unknown argument "filter" on field "Query.dmsPhysicalRwGoalSetting".],

code:--
test("allDmsPhysicalRoVwStoreMasters", async () => {
  //const data  = GetDashboardItemsData;
  await RunGraphQLQuery(
    // GraphQL query goes here:
    `query getGoalSettingsByGroupName($group_name: String, $store_id: String) {
      dmsPhysicalRwGoalSetting(filter: { groupName: { equalTo: $group_name },
      storeId: { equalTo: $store_id } }) {
        nodes {
          goalId
          goalName
          goalValue
          storeId
        }
      }
    }
      `,
    // GraphQL variables:
    {
      group_name: "abc",
      store_id: "1234",
    },
    // Additional props to add to `req` (e.g. `user: {session_id: '...'}`)
    {},
    // This function runs all your test assertions:
    async (json) => {
      
      expect(json.errors).toBeFalsy();
      expect(json.data).toBeTruthy();
      expect(json.data.allDmsPhysicalRoVwStoreMasters.totalCount).toBe(2);
      // expect(json.data.currentUser).toMatchObject({
      //     id: user.id,
      // });
    }
  );
});

**Comment by benjie** [comment]
Perhaps you've not installed the filter plugin? Please follow the issue template; I will not tell you again.

**Comment by libinvarkey** [comment]
@benjie thanks
