### ISSUE TITLE
Module not found in docker-  docker run [image]  test

### ISSUE THREAD

**Issue by libinvarkey** [graphile/starter#266]
Test suite failed to run

    Cannot find module '../../helpers' from 'queries/login.test.js'

       5 |   Teardown,
       6 |   Sanitize,
    >  7 | } = require("../../helpers");

Path was correct in local run. Work as expect in locally but not in docker

**Comment by benjie** [comment]
Please follow the issue template. What are the full steps to reproduce this from a clean checkout of starter?
