### ISSUE TITLE
scripts/start.js yarn silent flag not accepted by Yarn berry v3

### ISSUE THREAD

**Issue by hegelstad** [graphile/starter#270]
### Summary

https://github.com/graphile/starter/blob/b4849f788b480b4d1f8f6c7ec42bfbf32445f4e3/scripts/start.js#L16

YARN_SILENT flag not accepted by Yarn berry v3.

Possible future breaking change.

### Steps to reproduce

```bash
yarn set version berry
yarn set version 3.x
yarn start
```

### Expected results

I expect that the server will start.

### Actual results

Yarn reports error:

```bash
Usage Error: Unrecognized or legacy configuration settings found: silent - run "yarn config -v" to see the list of settings supported in Yarn (in <environment>)
```

**Comment by benjie** [comment]
Thanks for the heads up. Since this repo isn't designed to work with yarn berry I'm not particularly concerned about this right now, but will keep it in mind for the future :+1:
