### ISSUE TITLE
Extract the server code for authentication into a Postgraphile plugin?

### ISSUE THREAD

**Issue by lukaspili** [graphile/starter#28]
First of all, thanks for this starter project. I personally found it very helpful when learning Postgraphile and working on my first project:

1. it shows how Postgraphile features work together in practice;
2. it shows the best practices;
3. it's well documented, up-to-date and complete;
4. it drastically reduces costs of setting up a new project from scratch, especially for beginners.

Obviously it makes sense that the starter project contains an authentication solution. Most of real world apps require it. But having this solution hardcoded in the project has several drawbacks, IMO. An authentication solution is:
1. Quite complex when done right, lots of code, features and security requirements;
2. Critical, must be maintained and bug-free.

With this in mind, it might not match the goals of the starter project for the following reasons:
1. The project is intended to be used at "point in time". If an issue is discovered and fixed at a later date regarding the authentication, any previous user of the starter project won't get the fix easily;
2. The project is incredibly useful for beginners, as a tutorial/playground for learning Postgraphile. However the authentication code takes the big part of the spotlight. And it's not the best learning material. As said above, it's rather complex and domain-specific.

So what about extracting this code into a flexible authentication plugin, as an alternative to JWT + external auth solutions?
- It can evolve over time with security fixes and additional features;
- It will greatly simplify the starter project code and lower the barrier for beginners. The starter can then showcase a simpler model like a forum or a todo-list;
- Right now if a developer doesn't want to implement authentication manually, he's required to go with JWT and an external auth service. But I believe many developers would gladly not deal with the complexities of JWT for a simple auth. Coming from Ruby on Rails development, I know libraries like Devise (https://github.com/plataformatec/devise) are very popular and a go-to choice for implementing a simple, in-house auth system;
- For developers that just want the boilerplate code for auth in order to customize the code internally, cloning the starter project or cloning the auth plugin project is pretty much the same;

Now I understand it's big task to make it as an external plugin, especially to make it flexible and pluggable with the rest of the stack. But most of the work is already done in the starter project and it looks good!

I think it will be a great long-term addition to the Postgraphile ecosystem.
What do you think?

**Comment by benjie** [comment]
I'm going to close this because really this is a task for a separate repository which needs creating at some point.
