### ISSUE TITLE
Recommendations for disabling default mutations

### ISSUE THREAD

**Issue by singingwolfboy** [graphile/starter#53]
This project uses PostGraphile's [default CRUD mutations](https://www.graphile.org/postgraphile/crud-mutations/), which is perfectly reasonable and expected. However, when a developer takes this codebase and customizes it for their own project, they will probably turn off the default CRUD mutations in favor of [custom mutations](https://www.graphile.org/postgraphile/custom-mutations/) -- and at that point, things go a bit off the rails.

[GraphQL Code Generator](https://graphql-code-generator.com/) is designed to validate that our queries match our schema, but once these mutations are disabled, the queries no longer match, and running `yarn build` results in a lot of ugly errors. Furthermore, it's not immediately obvious that these errors are due to disabling the default mutations, since they involve code and queries that the developer didn't write and is not familiar with. Even after the developer determines the cause of the errors, it's not clear what is the best way to resolve the issue: delete the code? Disable graphql-codegen? Write custom mutations that match the autogenerated ones that you need? Something else?

To be clear, the problem here is _not_ using autogenerated mutations. That is a very handy feature for PostGraphile, and it makes sense to show it off in this repo. The problem is that there are no clear paths for how to disable this feature without breaking everything. This problem could be solved with documentation, with informative error messages, with a migration file that defines the database functions necessary to recreate these mutations, or some combination of these. (Maybe other ways, too?)

**Comment by benjie** [comment]
Closing this; it's an opinionated starter and I'm happy with the default CRUD mutations being (selectively) enabled as is the status quo.
