### ISSUE TITLE
tsc unable to compile imports from other workspaces in certain cases

### ISSUE THREAD

**Issue by jkantr** [graphile/starter#55]
### Problem
tsc is unable to navigate imports from any workspace in a workspace that is tsconfig configured with a `rootDir`. 

Repro: https://github.com/jkantr/starter/tree/repo_import__to_workspace_with_rootdir
Error: 

```
@app/server: error TS6059: File '/mnt/d/src/graphql-starter-repro/@app/graphql/index.tsx' is not under 'rootDir' '/mnt/d/src/graphql-starter-repro/@app/server/src'. 'rootDir' is expected to contain all source files.
```

This error persists even when added the workspace in question to the local deps. See:
https://github.com/jkantr/starter/blob/repo_import__to_workspace_with_rootdir/%40app/server/package.json#L15

### Solution:
Use TS3.0 Project References - example referencer tsconfig:
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "noEmit": false,
    "rootDir": "src",
    "outDir": "dist",
    "tsBuildInfoFile": "dist/tsconfig.tsbuildinfo",
    "declarationDir": "dist",
    "lib": ["es2018", "esnext.asynciterable"],
    "target": "es2018",
    "module": "commonjs"
  },
  "include": ["src"],
  "references": [{ "path": "../graphql" }]
}
```

Example refrencee tsconfig:
```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "jsx": "react",
    "target": "es2017",
    "module": "commonjs",
    "noEmit": false,
    "composite": true
  },
  "include": ["index.tsx"]
}
```

(the above with `@app/server` and `@app/graphql` fixes the error in the above repo branch)

### Possible Resolution:
Either include certain references / reference paths by default in the starter for workspaces with `rootDir`s or include a section in the README pertaining to this enhancement when needed.

**Comment by benjie** [comment]
I fixed this by adding the `"types"` entry to the relevant `package.json` files. I'm not certain that Next.js supports project references so I was hesitant to introduce that to the repo.
