### ISSUE TITLE
CI for master build failed on --noEmit, here's why

### ISSUE THREAD

**Issue by acao** [graphile/starter#64]
Looking at the last merge to master here, I can see the error for `error TS5072: Unknown build option '--noEmit'.`

I can see `noEmit` is set in config throughout:

https://github.com/graphile/starter/search?q=emit&unscoped_q=emit

however, when using `tsc --build` for project references, many of of your options change, and `noEmit` is one of the things you can no longer do. you do have the option of doing `tsc --build --dry` which is effectively the same.

https://www.typescriptlang.org/docs/handbook/project-references.html#tsc--b-commandline

**Comment by benjie** [comment]
Hey @acao; thanks for the issue. Master CI seems to be passing? https://github.com/graphile/starter/commit/cee85cc6f785198be40724b9a88d9171e75bc434/checks?check_suite_id=353491107

I think you might be looking at an older build, perhaps one on the `project-references` branch before I fixed this issue? (e.g. https://github.com/graphile/starter/commit/5685eb0aa687c95353dc4eaf5f53302282585f80/checks?check_suite_id=351530338)

`noEmit` seems to be fine in `tsconfig.json` files when using project references; it is simply ignored when you issue the `--build` flag. You're right that `--noEmit` on the CLI is not valid when combined with the `--build` flag, but we don't do this.

The reason we have `noEmit` in our `tsconfig.json` is that we don't want Next.js or Jest (which currently don't use project references in this repo) to output files, so we configure those with the noEmit default.

Interested to know where you're seeing this build error?

**Comment by benjie** [comment]
Closing as I don't think this is an issue.

**Comment by acao** [comment]
yeah it isn't my bad, was looking at the wrong build you are correct
