### ISSUE TITLE
CRA for apps without SSR

### ISSUE THREAD

**Issue by alexk111** [graphile/starter#66]
Having ```@app/client-cra``` for a Create-React-App based version of the ```@app/client``` might be a better option for apps that sit behind the login wall and don't need any SSR.

**Comment by rudin** [comment]
Here's a CRA version in the works. You might want to check it out:
https://github.com/rudin/graphile-starter-cra-js
This fork offers a version where the client is a regular 'create-react-app', in case you're not into TypeScript or already have your front-end lyin' round, like I do.
The register and login pages are set-up. Opinionated front-end with styled-components and styled-system comin' up.

**Comment by benjie** [comment]
Yeah I absolutely encourage this kind of thing in forks, and am happy adding links to different “flavours” in the README. This repo won’t be adding multiple alternative ways of doing things though, the key thing is that it’s opinionated.

@rudin You can use TypeScript with CRA. Removing TypeScript from the repo is quite a big deal; you can do that if you want but make sure you update the README and be aware merging in updates from upstream will be significantly harder.

https://create-react-app.dev/docs/adding-typescript/

**Comment by rudin** [comment]
I can surely create a branch with a typescript version of the CRA. Might even make that the master branch. Went for the non-typescript version because my specific usecase didn't 'need' typescript (front-end has been built without..)
Feel free to ad my 'flavour' to the README.

Thank you for your great work! I'll let you know when things are running in production.

**Comment by alexk111** [comment]
@rudin Will check the fork. It would be cool to have a TypeScript version of CRA to keep the code consistent. 

@benjie Got it. In that case, a curated list of links to different "flavors" looks like a good alternative!

**Comment by benjie** [comment]
If someone wants to start the list that'd be great. @JoeSchr I know you're working on a fork for Vue, you can add that to the list too :+1:

**Comment by benjie** [comment]
I reckon add a section below "Features" called "Variants" (make sure you add it to the TOC too).

**Comment by alexk111** [comment]
I've started working on a fork for CRA (Typescript). Will add it to the list when it's ready.
