### ISSUE TITLE
Possible session signing vulnerability

### ISSUE THREAD

**Issue by jkantr** [graphile/starter#74]
### Problem
The starter properly generates cryptographically  secure secrets in the setup script, but has a 'fallback' using a very dubious default:

https://github.com/graphile/starter/blob/aef2ac74830188c7e01e0418b7a57c01d356ed93/%40app/server/src/middleware/installSession.ts#L18

If one misconfigures their env vars after setup, or circumvents the setup, this could result in using a very insecure secret for session signing.

### Solution
Provide no default here and fail if there is no secret available.

**Comment by benjie** [comment]
👍PR welcome

**Comment by benjie** [comment]
Fixed but not tested in https://github.com/graphile/starter/commit/ad9f505307fa7c194cd57bd1b9763ad0b03e4e3c
