### ISSUE TITLE
Improve the setup script's wait-for-database functionality

### ISSUE THREAD

**Issue by charlex** [graphile/starter#75]
If the error code is 'ENOTFOUND' then it's not likely the attempt to setup the database will succeed. Perhaps change the code to:

```js
  // Wait for PostgreSQL to come up
  let attempts = 0;
  while (true) {
    try {
      await pgPool.query('select true as "Connection test";');
      break;
    } catch (e) {
      if (e.code === 'ENOTFOUND') {
        console.log(
          'Could not find database connection at host:',
          answers.DATABASE_HOST
        );
        process.exit(1);
      }
      attempts++;
      if (attempts <= 60) {
        console.log(`Database is not ready yet (attempt ${attempts})`);
      } else {
        console.log('Database never came up, aborting :(');
        process.exit(1);
      }
      await sleep(2000);
    }
  }
```

**Comment by benjie** [comment]
That’s not the only error code that’s expected, I think. Depends what DB you’re connecting to. In Docker, for example, I think it’s a connection refused error until the Docker spins up. You might get a timeout error. There’s also errors postgres might throw after listening but before it’s ready to handle this specific request. I do not have an exhaustive list of what the errors might be.

**Comment by benjie** [comment]
Closing this because I don't think it's this simple.
